services:
  app:
    build: .
    container_name: symfony_app
    # ports:
    #   - "8080:80"
    #   - "8443:443"
    volumes:
      - .:/app
    environment:
      TRUSTED_PROXIES: 0.0.0.0/0
      TRUSTED_HOSTS: ^api\.coding974\.com$
      APP_ENV: dev
      DATABASE_URL: "postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=18&charset=utf8"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - wordpress_shared_network

  database:
    image: postgres:${POSTGRES_VERSION:-18}-alpine
    container_name: symfony_db
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-app}",
          "-U",
          "${POSTGRES_USER:-app}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - wordpress_shared_network

volumes:
  database_data:

networks:
  wordpress_shared_network:
    external: true
